### ISSUE TITLE
npm build does not work on windows

### ISSUE THREAD

**Issue by jedfonner** [ModusCreateOrg/react-es6-webpack#1]
```
> react-es6-webpack@1.0.0 build C:\repo\training\react-es6-webpack
> NODE_ENV=production node_modules/.bin/webpack --progress --colors

'NODE_ENV' is not recognized as an internal or external command,
operable program or batch file.

npm ERR! Windows_NT 6.1.7601
```

I was able to solve this by adding a new `build:win` script as follows

`"build:win": "SET \"NODE_ENV=production\" && webpack --progress --colors"`

**Comment by emimuresan** [comment]
Thank you for filing this issue! :heart: 

We no longer maintain this repository, but we continue to work on the most cutting-edge open source projects. You can find amazing solutions and ideas on the [Modus Labs](https://labs.moduscreate.com?utm_source=github&utm_medium=issues&utm_campaign=deprecated) website.
